##00. PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors

### Creating tensors

https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [14]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX[0]

tensor([7, 8])

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([1, 3, 3])

In [22]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many NN learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

https://pytorch.org/docs/stable/generated/torch.rand.html

In [24]:
# Create a random tensor of size(3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4706, 0.8226, 0.2791, 0.4659],
        [0.1636, 0.3979, 0.3027, 0.2736],
        [0.9730, 0.6604, 0.7636, 0.6438]])

In [26]:
random_tensor.ndim

2

In [27]:
# Create a random tensor with similiar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channel (R, G B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [28]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
# Create tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
ones.dtype

torch.float32

In [32]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [38]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [49]:
# Float 32 tensors
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # e.g float32, float16
                               device=None,  # "cuda" What device is your tensor on
                               requires_grad=False) # Wether or not to track gradients value
float_32_tensor

tensor([3., 6., 9.])

In [50]:
float_32_tensor.dtype

torch.float32

In [52]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [53]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [54]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [55]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to do get datatype from tensor can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor `tensor.shape`
3. Tensors not on the right device - to get device from a tensor `tensor.device`

In [56]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9672, 0.1292, 0.4638, 0.6019],
        [0.6906, 0.1102, 0.9149, 0.0610],
        [0.7947, 0.1170, 0.6590, 0.3535]])

In [57]:
# Find out details some tensor
print(some_tensor)
print(f"Datatype: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")

tensor([[0.9672, 0.1292, 0.4638, 0.6019],
        [0.6906, 0.1102, 0.9149, 0.0610],
        [0.7947, 0.1170, 0.6590, 0.3535]])
Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


### Manipulating Tensors (tensor operation)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [66]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [67]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [68]:
# Substrac 10
tensor - 10

tensor([-9, -8, -7])

In [69]:
# Using built in
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

Two main ways to perform multiplication

1. Element-wise Multiplication
2. Matrix Multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match
* `(3, 2) @ (3, 2)` wont work
* `(2, 3) @ (3, 2)` will work
*`(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [70]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [71]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [74]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 3.62 ms, sys: 0 ns, total: 3.62 ms
Wall time: 6.82 ms


In [75]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 492 µs, sys: 26 µs, total: 518 µs
Wall time: 401 µs


tensor(14)

### One of the most common errors is deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                          [8, 11],
                          [9, 12]])

# torch.mm(tensor_A, tensor_B)

In [83]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix tensor shape issues, we can manipulate the shape of tensors using transpose

A **transpose** switches the axes or dimesion of given tensor

In [84]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [85]:
tensor_B.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [86]:
# The matrix multiplication operation works when tensor_B is transposed

torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean. sum, etc (tensor aggregation)

In [97]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [98]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [99]:
# Find mean - Requires float32 datatype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [100]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [101]:
x[x.argmin()]

tensor(1)

In [102]:
x[x.argmax()]

tensor(91)

## Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - Reshapes an input tensor to a defined shaped
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (Vstack) or side by side (Hstack)
* Squeeze - Remove all `1` diemnsions from a tensor
* Unsqueeze - Add `1` dimension to target tensor
* Permute - Return a view of the input dimensions permuted (swapped) in a certain way

In [129]:
# Let's create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [140]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [133]:
# Change the view
z = x.view(1, 9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [134]:
# Changing z changes x (beause a view of a tensor share same memory)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [135]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [142]:
# Squeeze tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"\nNew shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

New shape: torch.Size([9])


In [145]:
# Unsqueeze tensor
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add extra dimensions with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"\nNew shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

New shape: torch.Size([1, 9])


In [148]:
# Permute tensor - Rearrange in to spesific order
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to reaarange the axis (or dim) order
x_permuted = x_original.permute(2,  0, 1)

print(f"Prev shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Prev shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [149]:
x_original[0, 0, 0] = 77777
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(77777.), tensor(77777.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [151]:
# Create Tensor
x  = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [152]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [153]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [158]:
# Let's index on the last dimension
x[0][1][1]

tensor(5)

In [155]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [156]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [157]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [159]:
# Get index 0 and 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [162]:
# Index on x to return 9
x[0, 2, 2]

# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors and NumPy

NumPy is a popular scientific python numerical computing library

And because of this, PyTorch has functionality to interact with it

* Data in NumPy, want on PyTorch tensor -> `torch.from_numy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [165]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [166]:
# Change the value of array, what will this do to `Tensor`?

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [169]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [170]:
# Change the tensor, what happens to `numpy_tensor`
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how NN learns:

`Start with random numbers -> tensor operation -> update random numbers to try and make them better representations of the data -> again -> again...`

To reduce the randomness in NN and PyTorch comes the concept of a **random seed**

Essenstially what the random seed does is "flavour" the randomness

In [171]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2738, 0.7849, 0.0347, 0.4153],
        [0.1997, 0.1439, 0.5741, 0.5680],
        [0.7434, 0.8509, 0.5726, 0.8528]])
tensor([[0.2234, 0.7526, 0.1727, 0.4216],
        [0.7438, 0.7224, 0.3185, 0.3907],
        [0.1858, 0.8931, 0.9286, 0.2901]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [172]:
# Let's make some random but reporucible tensors

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs

GPUS = faster computation on numbers

In [2]:
!nvidia-smi

Sat Mar 23 10:16:33 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Check GPU access with PyTorch

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practise to setup device agnostic code

https://pytorch.org/docs/stable/notes/cuda.html#device-agnostic-code


In [4]:
torch.cuda.is_available()

True

In [5]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
# Count number of devices
torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU

In [10]:
# Create tensors (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [11]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU

In [12]:
# If tensor is on GPU, can't transform it to NumPy
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Exercises and Extra